### ISSUE TITLE
The godot-cpp sub-module needs to be updated to proper commit for GDExtension Summator project to load using Godot 4.0-beta2 

### ISSUE THREAD

**Issue by belal-sweileh** [paddy-exe/GDExtensionSummator#11]
Godot 4.0-Beta2
Windows 10

After compiling godot-cpp and summator gdextension as outlined in the readme, the Godot editor silently crashes upon opening the project. Then I noticed that the godot-cpp commit being used in this repo is be7ed4c, which is only compatible with Godot 4.0-beta1 and not Godot 4.0-beta2. Once I checked-out the correct commit for godot-cpp as outlined here (https://github.com/godotengine/godot-cpp/issues/874) and recompiled the godot-cpp sub-module and the Summator GDExtension, the project loaded without any problems. 

Just thought I'd let you know that the godot-cpp sub-module needs to be updated to the following commit to work with Godot 4.0-beta2:

https://github.com/godotengine/godot-cpp/commit/fa4d18f21cfae319b8f16a1604742cfec6022079

**Comment by paddy-exe** [comment]
@belal-sweileh Thanks for the notification!
With https://github.com/paddy-exe/GDExtensionSummator/pull/12 merged this closes this issue here
