### ISSUE TITLE
Identifier "Summator" not declared in the current scope

### ISSUE THREAD

**Issue by CarlCochet** [paddy-exe/GDExtensionSummator#2]
### Description:
 
The Summator example class is not recognized inside GDScript after compiling Godot 4, godot-cpp and the GDExtensionSummator. 

Platform: Windows 10, 64 bits
Godot commit version: 622806397
godot-cpp commit version: c4f12ccc3cd19b8fd535d179efd0471386c7f8e9

### Steps: 

- Clone Godot master branch
- Run `scons platform=windows`
- Clone GDExtensionSummator repository
- Go inside godot-cpp and run `scons target=debug generate_bindings=yes` 
- Go back to GDExtensionSummator root and run `scons target=debug`
- Launch Godot from `godot/bin/godot.windows.tools.64.exe`
- Create new project, add script to scene and write `var test = Summator.new()`

### Result: 

In the GDScript editor, we can see that `Summator` is not recognized: 
``` 
  res://Player.gd:5 - Parse Error: Identifier "Summator" not declared in the current scope.
  modules\gdscript\gdscript.cpp:874 - Method/function failed. Returning: ERR_PARSE_ERROR
```

![gdextension_error](https://user-images.githubusercontent.com/25507252/159141140-61b4153d-33f0-44c2-b80c-2cc34b9ec795.png)

Running the scene does not help, it fails at the line where I try to instanciate the `Summator` object. 
I also tried building the release versions for all components and got the same issue.

**Comment by paddy-exe** [comment]
@CarlCochet Would you mind running the project with the new Alpha 5 again? And with the latest version of godot-cpp. I tried it on both Mac and Windows and it works for me without any flaws.

**Comment by CarlCochet** [comment]
I tried again this morning, removed every Godot instances from my computer and cloned the newest master branch along with the newest godot-cpp + the extension, I followed the same steps again and it seems to work now! Thanks for the help

**Comment by paddy-exe** [comment]
Good to hear👍🏻
