### ISSUE TITLE
VSCode Intellisense?

### ISSUE THREAD

**Issue by scriptsengineer** [paddy-exe/GDExtensionSummator#54]
I saw that you use vscode, could you tell me what settings you managed to get intellisense?
- OS?
- CLang or C++ (Extension)?
- Use CMake?

**Comment by paddy-exe** [comment]
Hey @scriptsengineer 
I use both MacOS and Windows for development and the C++ extension for VSCode. Since I use SCons as build tool, there's no CMake here. Once you compile the godot-cpp folder you will get IntelliSense as far as I know and experienced myself.

**Comment by scriptsengineer** [comment]
Your Scons generating vsproj by default?

**Comment by paddy-exe** [comment]
> Your Scons generating vsproj by default?

Not that I know of, no
