### ISSUE TITLE
Running vscode tasks generates `.x86_64` libs, but `.gdextension` file looks for `.64` (Windows)

### ISSUE THREAD

**Issue by fenix-hub** [paddy-exe/GDExtensionSummator#6]
As the titles mentions, when running the tasks in vscode on Windows, libraries are automatically compiled and named to `libgdsummator.windows.debug.x86_64.*`, while `.gdextension` file in this repository looks for `.64` files.
Could be useful mentioning that the `.gdextension` file should be modified based on the system type, or giving some extra information about the setup in the README.

![image](https://user-images.githubusercontent.com/45271396/190852745-f446e481-2ae6-4427-9ee7-b3f4fe57dd53.png)

**Environment**
*Godot-cpp version:* the one recursively cloned from this template
*Godot Editor version:* 4.0 beta 1
*Windows:* Microsoft Windows 11 PRO Build 22622 x64

**Comment by paddy-exe** [comment]
@fenix-hub Thanks for the feedback! The issue is the same as in here: https://github.com/paddy-exe/GDExtensionSummator/issues/4
I will update the repo to the beta version in the next couple days since I am currently still on vacation.

**Comment by fenix-hub** [comment]
Thank you very much, enjoy your vacation :)

**Comment by paddy-exe** [comment]
@fenix-hub Can you try https://github.com/paddy-exe/GDExtensionSummator/pull/7 and see if this PR solves your issue?

**Comment by fenix-hub** [comment]
Yes it works now :)
But trying to export to Windows, after compiling for release, I get this error
```shell
Skipping export of out-of-project library summator/libsummator.windows.release.x86_64.dll
  Couldn't export extension: res://extension/summator.gdextension. No suitable library found for export flags: pc, s3tc, windows, x86_64, release
```
Do you happen to know why?

**Comment by paddy-exe** [comment]
> Yes it works now :)
> 
> But trying to export to Windows, after compiling for release, I get this error
> 
> ```shell
> 
> Skipping export of out-of-project library summator/libsummator.windows.release.x86_64.dll
> 
>   Couldn't export extension: res://extension/summator.gdextension. No suitable library found for export flags: pc, s3tc, windows, x86_64, release
> 
> ```
> 
> Do you happen to know why?

Great news 🙌🏼🎊 
About your bug: not sure what the cause of this could be to be honest... Does this happen as well with the godot-cpp demo project?

Edit: Maybe try to copy the first binary names from here: https://github.com/godotengine/godot-cpp/blob/master/test/demo/example.gdextension

**Comment by fenix-hub** [comment]
this is what I get when I try to export the godot-cpp demo project with the binaries compiled with scons
```
Couldn't find the given section "dependencies" and key "windows.release.x86_64", and no default was given.
```

**Comment by paddy-exe** [comment]
> this is what I get when I try to export the godot-cpp demo project with the binaries compiled with scons
> 
> ```
> 
> Couldn't find the given section "dependencies" and key "windows.release.x86_64", and no default was given.
> 
> ```

Could create a separate issue here with the above mentioned issue and also another issue on the Godot-cpp repository?
This seems to be an upstream issue
