### ISSUE TITLE
Node documentation example

### ISSUE THREAD

**Issue by bitbrain** [paddy-exe/GDExtensionSummator#8]
I am wondering how I would generate in engine docs tor custom nodes coming from a GDExtension? It would be phenomenal if this template extension could show how to do it.

**Comment by bitbrain** [comment]
@paddy-exe looks like stuff is happening: https://github.com/godotengine/godot/pull/67217

we might be able to do it now? Could you have a look?

**Comment by paddy-exe** [comment]
@bitbrain I had another look at it and you can already have custom docs in the editor that get's automatically generated with the Extension (whether it's a Node or a ReferenceObject):
There only seems to be a bug with the Argument names (but that could be on my side as well) 
![image](https://user-images.githubusercontent.com/38077837/195121177-f3270d49-f16d-4017-8711-e9704a91b5fd.png)
![image](https://user-images.githubusercontent.com/38077837/195121204-417cb111-742d-4685-b5c6-0b01280daf7a.png)

**Comment by bitbrain** [comment]
> in the editor that get's automatically generated with the Extension

@paddy-exe I remember someone saying that the automatic generation only works for debug builds (since the debug info is part of the extension so it can infer it). I'd expect us to require defining XML files like we do for Godot itself: https://github.com/godotengine/godot/tree/master/doc but I haven't seen any documentation about it how this would work with a GDExtension.

**Comment by paddy-exe** [comment]
@bitbrain Just to be on the same page: Do you mean by debug build the editor, the extension or both? Because compiling the extension for a release build still creates the docs

**Comment by bitbrain** [comment]
> Because compiling the extension for a release build still creates the docs

Interesting. How does it generate things like descriptions for signals methods /arguments without us having any .xml files specified?

**Comment by paddy-exe** [comment]
As far as I know this isn't even possible yet (at least considering the blog post announcement)
> [Help pages are automatically made available for your classes, detailing their properties, methods, signals, etc.: We're still working on the ability to also add descriptions to each.](https://godotengine.org/article/introducing-gd-extensions)

**Comment by bitbrain** [comment]
https://github.com/godotengine/godot/pull/67298 looks promising

**Comment by Splizard** [comment]
@bitbrain yes, the issue regarding _unamed_arg has been fixed. I'm not as familiar with the C++ extension interface and usage but if you know how to set the name of an argument it should be respected within the editor docs.

**Comment by paddy-exe** [comment]
> https://github.com/godotengine/godot/pull/67298 looks promising

Good to know! I will have a look when the next beta launches👍🏻

**Comment by paddy-exe** [comment]
@bitbrain @Splizard :
https://github.com/paddy-exe/GDExtensionSummator/pull/17
I merged some a PR that should address at least a bit of an enhancement for the class docs:
<img width="822" alt="image" src="https://user-images.githubusercontent.com/38077837/197410787-d02fdec8-d13f-4533-b1fd-b4125cf0ee8f.png">

**Comment by paddy-exe** [comment]
My latest PR introduces the ability to load documentation for GDExtension classes: https://github.com/paddy-exe/GDExtensionSummator/pull/66
