### ISSUE TITLE
Custom node icons

### ISSUE THREAD

**Issue by bitbrain** [paddy-exe/GDExtensionSummator#9]
I haven't figured this out myself yet but having a custom .svg icon for one of the nodes might be great.

**Comment by paddy-exe** [comment]
I created an issue in the godot-cpp repo for this since it's not exposed (afaik): https://github.com/godotengine/godot-cpp/issues/863

**Comment by paddy-exe** [comment]
This issue should be solved soon I think: https://github.com/godotengine/godot/pull/75472

**Comment by YuriSizov** [comment]
I didn't mention it in the PR, but icons need to come with `*.import` files alongside them, configured to scale and adjust colors with the editor (same principle as you now need to apply to icons added with an editor plugin). Perhaps this could be automated in some way as a build step.

**Comment by paddy-exe** [comment]
I will close this issue per merged docs PR from me for the official documentation: https://github.com/godotengine/godot-docs/pull/9383
